app/api/urls.py
from django.urls import path
from .views import ProductoSearchAPIView

app_name = 'api'

urlpatterns = [
    path('busqueda/', ProductoSearchAPIView.as_view(), name='producto-search'),
]

app/cash_register/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/', include('api.urls')), # Reemplaza 'myapp' con el nombre de tu aplicación
]

app/core/urls.py
import imp
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import include
from .forms import MyAuthForm
from django.views.generic.base import TemplateView #import TemplateView
from .views import *

urlpatterns = [
    path('login', LoginView.as_view(template_name='login.html', authentication_form=MyAuthForm,redirect_authenticated_user=True), name='login'),
    path('editar-usuario/', editar_usuario, name='editar_usuario'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('busqueda', views.busqueda, name='busqueda'),
    path('<int:id_carro>', views.caja, name='caja'),
    path('', lambda request: redirect('caja', id_carro=1)),
    path('agregar_instancia/', views.agregar_instancia, name='agregar_instancia'),
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('agregar_producto_al_carrito/<int:id_producto>/<int:cantidad>/<int:id_carro>/', views.agregar_producto_al_carrito, name='agregar_producto_al_carrito'),
    path('eliminar/<int:item_id>/<int:id_carro>', views.eliminar_item, name='eliminar_item'),
    path('ventas/', views.listar_ventas, name='listar_ventas'),  # Agrega esta línea
    path('venta/<int:venta_id>/', views.detalle_venta, name='detalle_venta'),
    path('informe-general/', views.informe_general, name='informe_general'),
    path('cerrar_caja/<monto_en_la_caja>', views.cerrar_caja, name='cerrar_caja'),
    path('editar-caja-diaria/', views.editar_monto_caja_diaria, name='editar_caja_diaria'),
    path('cuadrar/', views.cuadrar, name='cuadrar'),
    path('agregar_producto/', views.agregar_producto, name='agregar_producto'),
    path('imprimir/', views.imprimir, name='imprimir'),
    path('verificar-actualizaciones/', check_updates, name='verificar-actualizaciones'),
    path('abrir-caja/', views.abrir_caja, name='abrir-caja'),
    path('generate_barcode/', views.generate_barcode, name='generate_barcode'),
    path('crear_usuario/', views.crear_usuario, name='crear_usuario'),
    path('imprimir_boleta/<int:venta_id>/', views.imprimir_boleta, name='imprimir_boleta'),
    path('seleccionar_metodo_pago/<int:id_carro>/', views.seleccionar_metodo_pago, name='seleccionar_metodo_pago'),
    path('procesar_pago/<int:id_carro>/', views.procesar_pago, name='procesar_pago'),
    path('ingresar_monto_efectivo/<int:id_carro>/', views.ingresar_monto_efectivo, name='ingresar_monto_efectivo'),
    path('seleccionar_metodo_pago_resto/<total>/<monto_efectivo>/<int:id_carro>/', seleccionar_metodo_pago_resto, name='seleccionar_metodo_pago_resto'),
    path('procesar_pago_restante/<metodo_pago>/<restante>/<int:id_carro>/', views.procesar_pago_restante, name='procesar_pago_restante'),
    path('ventas-respaldo/', views.listar_ventas_respaldo, name='listar_ventas_respaldo'),
    path('ventas-respaldo/<int:venta_respaldo_id>/', views.detalle_venta_respaldo, name='detalle_venta_respaldo'),
    path('eliminar-venta/<int:venta_id>/', views.eliminar_venta, name='eliminar_venta'),
    path('ingresar-gasto/', views.ingresar_gasto, name='ingresar_gasto'),
    path('gastos/', views.lista_gastos, name='lista_gastos'),
    path('configuracion/edit/', ConfiguracionUpdateView.as_view(), name='config'),
    path('cambiar_clave/<int:user_id>/', views.cambiar_clave_usuario, name='cambiar_clave_usuario'),
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('lista_usuarios_desabilitados/', views.lista_usuarios_desabilitados, name='lista_usuarios_desabilitados'),
    path('usuarios/eliminar/<int:user_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('usuarios/activar/<int:user_id>/', views.activar_usuario, name='activar_usuario'),
    path('generar_codigo_ean13/', views.generar_y_imprimir_codigo_ean13, name='generar_codigo_ean13'),
    path('generar_venta/<tipo_pago>/<restante>/<vuelto_inicial>/<int:id_carro>/', views.generar_venta, name='generar_venta'),
    path('vaciar_carrito/<int:id_carro>/', views.vaciar_carrito, name='vaciar_carrito'),
    path('productos/', ProductoListView.as_view(), name='producto-list'),
    path('producto/editar/<int:pk>/', ProductoEditarView.as_view(), name='producto-editar'),  # Define la URL de edición
    path('impresora-no-conectada/', impresora_no_conectada, name='impresora_no_conectada'),
    path('impresora-si-conectada/', impresora_si_conectada, name='impresora_si_conectada'),
    path('cambiar_usuario/<int:usuario_id>/', cambiar_usuario, name='cambiar_usuario'),
    path('cambiar_clave_anulacion/<int:usuario_id>/', cambiar_clave_anulacion, name='cambiar_clave_anulacion'),
    path('agregar_producto_rapido/<int:producto_id>/', agregar_producto_rapido, name='agregar_producto_rapido'),
    path('eliminar_producto_rapido/<int:producto_id>/', eliminar_producto_rapido, name='eliminar_producto_rapido'),
    path('general_dia_especifico/', general_dia_especifico, name='general_dia_especifico'),
    path('ventas_dia_especifico/', ventas_dia_especifico, name='ventas_dia_especifico'),
    path('ingresar_clave/<str:vista>/', ingresar_clave, name='ingresar_clave'),
    path('eliminar-producto/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('exportar-productos/', exportar_productos, name='exportar_productos'),
    path('importar-productos/', importar_productos, name='importar_productos'),
    path('exportar-productos-periodico/', views.exportar_productos_periodico, name='exportar_productos_periodico'),
    path('clave/<str:vista_destino>/', views.vista_intermedia_clave, name='vista_intermedia_clave'),

    
]

    


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.db.models.signals import pre_delete,post_migrate
from django.db.utils import IntegrityError
from math import ceil
# models.py

import logging

logger = logging.getLogger(__name__)

class Usuario(AbstractUser):
    # Define las opciones de permisos como una tupla de tuplas
    PERMISOS_CHOICES = (
        ('cajero', 'Cajero'),
        ('admin', 'Administrador'),
        ('bodeguero', 'Bodeguero'),
    )
    VENTAS_CHOICES = (
        ('pruebas', 'Ventas de Pruebas'),
        ('normales', 'Sistema de Ventas Normales (Se registran)'),
    )
    
    foto_perfil = models.ImageField(upload_to='fotos_perfil/', null=True, blank=True)
    ventas_config = models.CharField(max_length=40, choices=VENTAS_CHOICES, default='normales')
    permisos = models.CharField(max_length=40, choices=PERMISOS_CHOICES, default='cajero')
    
    rut = models.CharField(max_length=40, null=True, verbose_name="Rut", default="", blank=True)
    clave_anulacion = models.CharField(max_length=20, default="", unique=True)  # Hacer la clave única


# Define la función para crear el usuario admin
def crear_usuario_admin(**kwargs):
    if not Usuario.objects.filter(username='admin').exists():
        Usuario.objects.create_superuser(username='admin', password='123', clave_anulacion='123', permisos='admin')
        print("Usuario administrador creado exitosamente.")

# Registra la función con la señal post_migrate
@receiver(post_migrate)
def post_migrate_callback(sender, **kwargs):
    crear_usuario_admin(**kwargs)

    # Resto de los campos y métodos de tu modelo

class Departamento(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    id_producto = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    valor_costo = models.DecimalField(max_digits=12, decimal_places=2, default=0 )
    precio = models.DecimalField(max_digits=12, decimal_places=2)
    codigo_barras = models.CharField(max_length=20, unique=True, blank=True, null=True)
    gramaje = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    foto = models.ImageField(upload_to='productos/', null=True, blank=True, default='productos/default.jpg')
    descripcion = models.TextField(blank=True, null=True)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, related_name='productos_departamento', blank=True, null=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE, blank=True, null=True)
    TIPO_GRAMAJE_CHOICES = (
        ('kg', 'Kilogramos'),
        ('g', 'Gramos'),
        ('Ml', 'Mililitros'),
        ('L', 'Litros'),
    )
    tipo_gramaje = models.CharField(max_length=2, choices=TIPO_GRAMAJE_CHOICES, blank=True, null=True)

    TIPO_VENTA_CHOICES = (
        ('unidad', 'Artículo por unidad'),
        ('gramaje', 'Artículo por gramaje'),
        ('valor', 'Articulo por valor')
    )
    
    tipo_venta = models.CharField(max_length=10, choices=TIPO_VENTA_CHOICES, blank=False, null=False,default="unidad")
    

    def __str__(self):
        return self.nombre

class ProductoRapido(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)

    def __str__(self):
        return f"Producto rapido id {self.id} - {self.producto.nombre}"


class Stock(models.Model):
    producto = models.OneToOneField(Producto, on_delete=models.CASCADE, primary_key=True)
    cantidad = models.PositiveIntegerField(default=0)
    gramaje = models.PositiveIntegerField(default=0)
    TIPO_GRAMAJE_CHOICES = (
        ('kg', 'Kilogramos'),
        ('g', 'Gramos'),
    )
    tipo_gramaje = models.CharField(max_length=2, choices=TIPO_GRAMAJE_CHOICES, blank=True, null=True)

    def __str__(self):
        return f"Cantidad de {self.producto.nombre}: {self.cantidad}"



class CarritoItem(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    carrito_numero = models.PositiveIntegerField(default=1)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    gramaje = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    fecha_agregado = models.DateTimeField(auto_now_add=True)
    valor =  models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
        
    def subtotal(self):
        if self.producto.tipo_venta == 'gramaje':
            peso_en_gramos = self.gramaje
            if self.producto.tipo_gramaje == 'kg':
                subtotal = peso_en_gramos * (self.producto.precio / 1000)
            else:
                subtotal = peso_en_gramos * self.producto.precio
        elif self.producto.tipo_venta == 'valor':
            subtotal = self.valor * self.cantidad
        else:
            subtotal = self.cantidad * self.producto.precio

        # Redondea el subtotal al próximo múltiplo de 10 y asegura que no sea menor que 10.
        subtotal = max(10, ceil(subtotal / 10) * 10)

        return subtotal
    
class Configuracion(models.Model):
    id = models.AutoField(primary_key=True)
    decimales = models.PositiveIntegerField(default=2)
    clave_anulacion = models.CharField(max_length=20)
    idioma = models.CharField(max_length=20)
    imprimir_opciones = (
        ('no', 'No imprimir'),
        ('con_corte', 'Imprimir con corte'),
        ('sin_corte', 'Imprimir sin corte'),
    )
    tipo_de_venta = (
        ('1', 'No registrar Stock'),
        ('2', 'Registrar Stock con Descuento'),
        ('3', 'Registrar el stock de las ventas'),
    )
    separador_opciones = (
        ('1', 'Separar números por un < . > '),
        ('2', 'Separar números por un < , >'),
    )
    imprimir = models.CharField(max_length=20, choices=imprimir_opciones, default='no')
    separador= models.CharField(max_length=20, choices=separador_opciones, default='1')
    tipo_venta = models.CharField(max_length=20, choices=tipo_de_venta, default='1')
    porcentaje_iva = models.DecimalField(max_digits=5, decimal_places=2, default=0.0)
    
    # Agrega el campo para el tamaño de letra
    tamano_letra = models.PositiveIntegerField(default=10)  # Ejemplo: tamaño de letra por defecto de 10 puntos

    def __str__(self):
        return 'Configuración de la Aplicación'

@receiver(post_migrate)
def crear_configuracion(sender, **kwargs):  # Reemplaza 'tu_app_nombre' con el nombre de tu aplicación
        configuracion, created = Configuracion.objects.get_or_create(
            decimales = 0,
            clave_anulacion = '5901234123457',
            idioma = 'es',
            imprimir = 'sin_corte',
            porcentaje_iva = 0.0,
            tipo_venta = '1',
            tamano_letra = 30,
            separador = '1',
        )


class Venta(models.Model):
    id = models.AutoField(primary_key=True)
    fecha_hora = models.DateTimeField(default=timezone.now)
    productos = models.ManyToManyField(Producto, through='VentaProducto')
    total = models.DecimalField(max_digits=10, decimal_places=2)
    vuelto = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    # Otros campos según tus necesidades

    def __str__(self):
        return f'Venta #{self.id} - {self.fecha_hora}'

    class Meta:
        verbose_name_plural = 'Ventas'

class VentaProducto(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(blank=True, null=True)
    gramaje = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)
    # Otros campos relacionados con la venta de cada producto

    def __str__(self):
        return f'{self.producto} en Venta #{self.venta.id}'

class FormaPago(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    # Agregar campo para el tipo de pago
    TIPO_PAGO_CHOICES = (
        ('efectivo', 'Efectivo'),
        ('transferencia', 'Transferencia'),
        ('debito', 'Débito'),
        ('credito', 'Crédito'),
    )
    tipo_pago = models.CharField(max_length=20, choices=TIPO_PAGO_CHOICES)
    monto = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.tipo_pago} - Monto: {self.monto}'
    

class RegistroTransaccion(models.Model):
    id = models.AutoField(primary_key=True)
    fecha_ingreso = models.DateTimeField(default=timezone.now)
    monto_total = models.DecimalField(max_digits=10, decimal_places=2)

    # Detalles de los montos por tipo de pago
    monto_efectivo = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    monto_credito = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    monto_debito = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    monto_transferencia = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    monto_retiro = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    

    # Campo para el valor de la caja diaria
    valor_caja_diaria = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f'Registro #{self.id} - Fecha: {self.fecha_ingreso} - Monto Total: {self.monto_total}'
    
class CajaDiaria(models.Model):
    id = models.AutoField(primary_key=True)
    monto = models.DecimalField(max_digits=10, decimal_places=2,default=0.0)

app/core/templates/detalle_venta.html
{% extends 'base/nav.html' %}


{% block body %}
<div class="container-fluid">
    <h1 class="h3 mb-4" id="titulo">Detalle de Venta</h1>
    <div class="row">
        <div class="col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-body resize-text solofondo">
                    <h5>ID de Venta: {{ venta.id }}</h5>
                    <p>Fecha y Hora: {{ venta.fecha_hora }}</p>
                    <p>Vuelto: <span class="subtotal">{{ venta.vuelto|floatformat:configuracion.decimales }}</span></p>

                    <p>Total: <span class="subtotal">{{ venta.total|floatformat:configuracion.decimales  }}</span></p>

                    <h3>Productos Vendidos:</h3>
                    <ul>
                        {% for producto_vendido in productos_vendidos %}
                            {% if producto_vendido.cantidad != 0 %}
                            <li>{{ producto_vendido.producto.nombre }} - Cantidad: {{ producto_vendido.cantidad }}
                            <br>Subtotal: <span class="subtotal">{{ producto_vendido.subtotal|floatformat:configuracion.decimales }}</span></li>
                            {% else %}
                            <li>{{ producto_vendido.producto.nombre }} - Cantidad: {{ producto_vendido.gramaje|floatformat:configuracion.decimales }} Gramos
                            <br>Subtotal: <span class="subtotal">{{ producto_vendido.subtotal|floatformat:configuracion.decimales }}</span></li>
                            {% endif %}
                            <!-- Puedes agregar más detalles del producto vendido si es necesario -->
                        {% endfor %}
                    </ul>

                    <h3>Información de Pago:</h3>
                    <ul>
                        {% for forma_pago in formas_pago %}
                            <li>Tipo de Pago: {{ forma_pago.get_tipo_pago_display }} - Monto: <span class="subtotal">{{ forma_pago.monto|floatformat:configuracion.decimales  }}</span></li>
                            <!-- Puedes agregar más detalles de la forma de pago si es necesario -->
                        {% endfor %}
                    </ul>
                    
                    <a id="botonVolver" class="btn btn-secondary">Volver</a>
                    <a href="#" id="imprimir-venta" class="btn boton-dinamico">Imprimir Venta</a>
                    <div id="resultado-impresion"></div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'base/footer.html' %}
<!-- End of Footer -->


<!-- End of Content Wrapper -->
{% include 'base/logout.html' %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const imprimirVentaButton = document.getElementById("imprimir-venta");
        const resultadoImpresion = document.getElementById("resultado-impresion");
        const ventaId = {{ venta.id }}; // Obtén el ID de la venta desde el contexto Django
    
        imprimirVentaButton.addEventListener("click", function(event) {
            event.preventDefault(); // Evita que el enlace siga su URL original
    
            // Realiza una petición AJAX para imprimir la venta
            fetch(`{% url 'imprimir_boleta' venta.id %}`)
                .then(response => response.text())
                .then(data => {
                    resultadoImpresion.innerHTML = data; // Actualiza el contenido del div con la respuesta
                })
                .catch(error => {
                    console.error("Error al imprimir la venta:", error);
                });
        });
    });
    </script>

    <script>
        document.getElementById('botonVolver').addEventListener('click', function() {
            // Utiliza el historial del navegador para volver a la página anterior
            window.history.back();
        });
    </script>
    

{% endblock %}

app/core/templates/editar_clave_anulacion.html
{% extends 'base/nav.html' %}

{% block body %}
{% load static %}

<div class="container mt-5 mb-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body solofondo">
          <h5 class="card-title">Cambiar Clave anulación</h5>
          <form method="post">
            {% csrf_token %}

            {% if messages %}
            <div class="alert alert-success">
               <ul class="m-0">
                  {% for message in messages %}
                  <li>{{ message }}</li>
                  {% endfor %}
               </ul>
            </div>
            {% endif %}

            {{ form.as_p }}
            <button type="submit" class="btn boton-dinamico">Guardar Cambios</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'base/footer.html' %}
<!-- End of Footer -->


<!-- End of Content Wrapper -->
{% include 'base/logout.html' %}

{% endblock %}

app/core/templates/general_dia_especifico.html
{% extends 'base/nav.html' %}

{% block body %}



<div class="container-fluid">
    <h1 class="h3 mb-4" id="titulo">General Dia especifico</h1>
    <form method="GET" action="#" class="mb-4">
        <div class="form-row resize-text">
            <div class="col">
                <input type="date" name="fecha" class="form-control resize-text onlyinput" placeholder="Fecha" value="{{ request.GET.fecha }}">
            </div>
            <div class="col">
                <input type="time" name="hora" class="form-control resize-text onlyinput" placeholder="Hora" value="{{ request.GET.hora }}">
            </div>
            <div class="col">
                <button type="submit" class="btn boton-dinamico resize-text">Buscar</button>
            </div>
        </div>
    </form>
    


    <form id="imprimir-form" method="post">
        {% csrf_token %}
        <button type="submit" class="btn boton-dinamico mb-4">Imprimir</button>
    </form>
    <div class="row">
        <div class="col-lg-12">
            {% if request.GET.fecha and request.GET.hora %}
                <a href="{% url 'ventas_dia_especifico' %}?fecha={{ request.GET.fecha }}&hora={{ request.GET.hora }}" class="btn boton-dinamico mb-4">Ir a Detalle de Ventas</a>
            {% endif %}
        </div>
    </div>
    {% if request.GET.fecha and request.GET.hora %}    
    <div class="row">
        
        <div class="col-lg-12">
            
            <div class="card shadow mb-4">
                
                <div class="card-body resize-text solofondo">
                
                    <p>Total en Efectivo: <span class="subtotal">{{total_efectivo|floatformat:configuracion.decimales}}</span></p>
                    <p>Total en Débito: <span class="subtotal">{{total_debito|floatformat:configuracion.decimales}}</span></p>
                    <p>Total en Transferencia: <span class="subtotal">{{total_transferencia|floatformat:configuracion.decimales}}</span></p>
                    <p>Total de Retiro: <span class="subtotal">{{total_retiro|floatformat:configuracion.decimales}}</span></p>
                    <p>Total de gastos: <span class="subtotal">{{total_gastos|floatformat:configuracion.decimales}}</span></p>
                    <p>Caja diaria: <span class="subtotal">{{valor_caja_diaria|floatformat:configuracion.decimales}}</span></p> 
                </div>
            </div>
        </div>
    </div>

    {% if total >= 0 %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-body resize-text solofondo">
                    <h3>Totales Generales</h3>
                    {% comment %} <p>Total Bruto General: ${{ total_bruto_general.total_bruto|floatformat:configuracion.decimales }}</p> {% endcomment %}
                    <p>Total Neto General: <span class="subtotal">{{total|floatformat:configuracion.decimales}}</span></p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Totales por departamento -->
    {% comment %} <div class="row">
        <div class="col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-body resize-text solofondo">
                    <h3>Totales por Departamento</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Departamento</th>
                                <th>Total Bruto</th>
                                <th>Total Neto</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for venta_por_departamento in ventas_por_departamento %}
                            <tr>
                                {% if venta_por_departamento.departamento == None %}
                                <td>Sin Depto</td>
                                {% else %}
                                <td>{{ venta_por_departamento.departamento }}</td>
                                {% endif %}
                                <td>$</td>
                                <td>$</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div> {% endcomment %}

</div>
{% endif %}


{% include 'base/footer.html' %}
<!-- End of Footer -->


<!-- End of Content Wrapper -->
{% include 'base/logout.html' %}
{% endblock %}

app/core/templates/generate_barcode.html
{% extends 'base/nav.html' %}

{% block body %}
<div class="container-fluid">
    <h1 class="h3 mb-4" id="titulo">Contraseña de anulación</h1>
    <div class="row">
        <div class="col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-body solofondo">
                    {% if image_url %}
                    <h2>Código de Barras:</h2>
                    <div class="row">
                        <div class="col-lg-12">
                            <button class="btn btn-primary mb-4" onclick="imprimirCodigoBarras()">Imprimir Código de Barras</button>
                        </div>
                    </div>
                    <img src="{{ image_url }}" alt="Código de Barras GS1 (EAN-13)" class="img-fluid">
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>

{% include 'base/footer.html' %}
<!-- End of Footer -->


<!-- End of Content Wrapper -->
{% include 'base/logout.html' %}

<script>
function imprimirCodigoBarras() {
    const nuevaVentana = window.open('', '_blank');
    
    // Crea un documento HTML en la nueva ventana
    const contenido = `
        <html>
        <head>
            <title>Código de Barras</title>
        </head>
        <body>
            <h2>Código de Barras:</h2>
            <img src="{{ image_url }}" alt="Código de Barras GS1 (EAN-13)" class="img-fluid">
        </body>
        </html>
    `;
    
    nuevaVentana.document.open();
    nuevaVentana.document.write(contenido);
    nuevaVentana.document.close();
    
    // Espera a que se cargue la imagen antes de imprimir
    nuevaVentana.addEventListener('load', function() {
        nuevaVentana.print();
    });
}
</script>
{% endblock %}

app/core/templates/login.html
{% load static %}
{% if messages %}
{% for message in messages%}
<div class="notifi">
    {{message}}
</div>
{% endfor%}
{%endif%}
{% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="notifi">
             ingreso un dato incorrecto
        </div>
        {% endfor %}
      </div>
 {% endif %}
<!DOCTYPE html>
<html lang="es">
<head>
	<title>Login Caja Registradora</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="EL login de una pagina Web.">
	<link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}">
    <link rel="icon" href="{% static "favicon.ico" %}" type="image/x-icon">
    {% include 'base/tamaño_letra.html' %}
</head>
<body class="light-mode">
    <div class="loginBox"> <img class="user" src="{% static "img/banner.png" %}" height="100px" width="100px" alt="imagen perfil">
        <h3 class="resize-text">Inicia sesión Aquí</h3>
        <form method="post">
            <div class="inputBox resize-text"> 
                {% csrf_token %}
                {{form.username}}
                {% csrf_token %}
                {{form.password}}
            </div> 
            <input type="submit" name="" value="Login">
        </form> 

        
    </div>
</body>
</html>